@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequence {
	ReferenceBackgroundColor #FFFFFF
	ReferenceBorderColor #333333
}

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "context:CommandContext" as CommandContext LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

ref over LogicManager
Parse and route delete command
end ref

create CommandContext
LogicManager -> CommandContext : CommandContext(model, currentMode)
activate CommandContext
CommandContext --> LogicManager : context
deactivate CommandContext

LogicManager -> Model : getFilteredPersonList(currentMode)
activate Model
Model --> LogicManager : lastShownList
deactivate Model

LogicManager -> Model : deletePerson(personToDelete, currentMode)
activate Model
Model --> LogicManager
deactivate Model

create CommandResult
LogicManager -> CommandResult : CommandResult(feedback)
activate CommandResult
CommandResult --> LogicManager : r
deactivate CommandResult

[<-- LogicManager : r
deactivate LogicManager
@enduml
