@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam classBackgroundColor<<ghost>> transparent
skinparam classBorderColor<<ghost>> transparent
skinparam classFontColor<<ghost>> transparent
hide stereotype

package "Parser classes" {
    class "<<interface>>\nParser" as Parser
    class AddressBookParser
    class CommandRegistry
    class XYZCommandParser
    class "{abstract}\nCommand" as Command
    class XYZCommand
    class ArgumentMultimap
    class ArgumentTokenizer
    class CliSyntax
    class ParserUtil
    class Prefix
}

class IncomingArrow <<ghost>>

IncomingArrow .down.> AddressBookParser
AddressBookParser -down-> CommandRegistry

XYZCommandParser .up.|> Parser
CommandRegistry .down.> XYZCommandParser : <<create>>
CommandRegistry .right.> Command : <<use>>

XYZCommandParser .left.> ArgumentMultimap
XYZCommandParser .left.> ArgumentTokenizer
XYZCommandParser .down.> CliSyntax
XYZCommandParser .right.> ParserUtil
XYZCommandParser .right.> XYZCommand : <<create>>

ArgumentTokenizer .left.> ArgumentMultimap
ArgumentTokenizer .down.> Prefix
CliSyntax .down.> Prefix
ParserUtil .down.> Prefix

XYZCommand -up-|> Command
@enduml
